# Generated by Django 4.1.1 on 2022-09-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=420)),
                ('pic', models.URLField(max_length=430)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('original_link', models.URLField(max_length=460)),
                ('description', models.TextField(max_length=1500)),
                ('additional_desc', models.TextField(default='', max_length=1500)),
                ('material', models.TextField(default='', max_length=440)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weight_unit', models.CharField(default='', max_length=4)),
                ('color', models.CharField(default='', max_length=450)),
                ('dimension_length', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dimension_width', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dimension_height', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dimension_unit', models.CharField(default='', max_length=4)),
                ('isProduct', models.BooleanField(default=True)),
                ('furniture_location', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('event_type', models.CharField(max_length=10)),
                ('product_id', models.IntegerField()),
                ('timestamp_in', models.DateTimeField()),
                ('timestamp_out', models.DateTimeField(null=True)),
                ('timestamp_delta', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
