# Generated by Django 4.1 on 2022-09-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vect_color',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vect_desciption',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vect_mateial',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vect_name',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
