# Generated by Django 4.1 on 2022-09-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_item_vect_color_item_vect_desciption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_feature', models.TextField(max_length=4000, null=True)),
                ('color_feature', models.TextField(max_length=4000, null=True)),
                ('material_feature', models.TextField(max_length=4000, null=True)),
                ('description_feature', models.TextField(max_length=4000, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='vect_desciption',
            new_name='vect_description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='vect_mateial',
            new_name='vect_material',
        ),
    ]
