# Generated by Django 4.1 on 2022-09-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('other_product_id', models.IntegerField()),
                ('name_distance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('description_distance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('material_distance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('weight_distance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('color_distance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('dimension_length_distance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('dimension_width_distance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('dimension_height_distance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('furniture_location_distance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
            ],
        ),
    ]
