# Generated by Django 4.1 on 2022-09-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_features_dimension_height_feature_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distances',
            new_name='Distance',
        ),
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
    ]
