# Generated by Django 4.1 on 2022-09-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_item_normalized_dimension_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='normalized_dimension_height',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='normalized_dimension_length',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='normalized_dimension_width',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='normalized_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True),
        ),
    ]
