# Generated by Django 4.1 on 2022-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_item_normalized_dimension_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='normalized_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True),
        ),
    ]
