# Generated by Django 4.1 on 2022-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_item_normalized_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='price_distance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
