# Generated by Django 4.1 on 2022-09-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_distance_price_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='furniture_location_feature',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vect_furniture_location',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
