# Generated by Django 4.1 on 2022-09-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_feature_furniture_location_feature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='dimension_height_distance',
            new_name='dimension_distance',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='normalized_dimension_height',
            new_name='normalized_dimension',
        ),
        migrations.RemoveField(
            model_name='distance',
            name='dimension_length_distance',
        ),
        migrations.RemoveField(
            model_name='distance',
            name='dimension_width_distance',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='dimension_height_feature',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='dimension_length_feature',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='dimension_width_feature',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='weight_feature',
        ),
        migrations.RemoveField(
            model_name='item',
            name='normalized_dimension_length',
        ),
        migrations.RemoveField(
            model_name='item',
            name='normalized_dimension_width',
        ),
    ]
