# Generated by Django 4.1 on 2022-10-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_dimension_height_distance_distance_dimension_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='total_distance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
