# Generated by Django 4.1 on 2022-10-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_distance_total_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='temp_distance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
