# Generated by Django 4.1.2 on 2022-10-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_distance_temp_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
