# Generated by Django 4.1.2 on 2022-12-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_distance_color_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='normalized_dimension',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='normalized_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='normalized_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True),
        ),
    ]
