# Generated by Django 4.1.2 on 2022-12-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_item_normalized_dimension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='normalized_dimension',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='normalized_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='normalized_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
