# Generated by Django 4.1.2 on 2023-01-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_item_normalized_dimension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('views', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('see_original', models.IntegerField()),
                ('copied_phone', models.IntegerField()),
                ('copied_address', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='vect_color',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='vect_furniture_location',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
