# Generated by Django 4.1.2 on 2023-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_itemdetail_alter_item_vect_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='feature_added',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='vect_description',
            field=models.TextField(max_length=12000, null=True),
        ),
    ]
