# Generated by Django 4.1.2 on 2023-02-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_distance_feature_added_alter_item_vect_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=420)),
                ('pic', models.URLField(max_length=430)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('original_link', models.URLField(max_length=460)),
                ('description', models.TextField(max_length=1500)),
                ('additional_desc', models.TextField(default='', max_length=1500)),
                ('material', models.TextField(default='', max_length=440)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weight_unit', models.CharField(default='', max_length=4)),
                ('color', models.CharField(default='', max_length=450)),
                ('dimension_length', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dimension_width', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dimension_height', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dimension_unit', models.CharField(default='', max_length=4)),
                ('isProduct', models.BooleanField(default=True)),
                ('furniture_location', models.CharField(default='', max_length=100)),
                ('vect_name', models.TextField(max_length=4000, null=True)),
                ('vect_color', models.TextField(max_length=500, null=True)),
                ('vect_material', models.TextField(max_length=4000, null=True)),
                ('vect_description', models.TextField(max_length=12000, null=True)),
                ('vect_furniture_location', models.TextField(max_length=100, null=True)),
                ('normalized_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('normalized_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('normalized_dimension', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
