# Generated by Django 4.1.2 on 2023-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_tempitem_item_created_at_item_modified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
